// Brskalniški preizkus klepeta (ročno, ni del 'node --test'). Potrebuje: npm i puppeteer-core, Chrome (CHROME=/pot), strežnik na :8787
// z db.json z uporabnikoma u-ana (vodja) in u-bor (delavec) ter praznim data/chat. Poženi: node deploy/lan/tests/smoke-chat.mjs
import puppeteer from 'puppeteer-core'
const BASE = 'http://localhost:8787'
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const browser = await puppeteer.launch({ executablePath: process.env.CHROME || '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox'] })
let fails = 0
const ok = (c, m) => { console.log((c ? 'OK   ' : 'FAIL ') + m); if (!c) fails++ }
async function userPage(id, name, role, hash) {
  const ctx = await browser.createBrowserContext()
  const page = await ctx.newPage()
  await page.setViewport({ width: 1100, height: 800 })
  page.on('pageerror', (e) => { console.log('PAGEERROR', e.message); fails++ })
  await page.evaluateOnNewDocument((s) => localStorage.setItem('nabava-orodjarna-session-v2', JSON.stringify(s)), { userId: id, role, displayName: name })
  await page.goto(BASE + '/' + hash, { waitUntil: 'networkidle2' })
  return page
}
const A = await userPage('u-ana', 'Ana', 'vodja', '#/klepet/plani')
const B = await userPage('u-bor', 'Borut', 'delavec', '#/klepet/plani')
await A.waitForSelector('.chat textarea'); await B.waitForSelector('.chat textarea')
const names = await A.$$eval('.chat-ch-name', (e) => e.map((x) => x.textContent))
ok(JSON.stringify(names) === JSON.stringify(['Splošno', 'Plani', 'Nujno', 'Razno', 'Borut']), 'kanali v UI: ' + names.join(','))
// Ana sends with machine tag
await A.click('.chat-machine-btn'); await A.click('[data-machine="Okuma Genos"]')
await A.type('.chat textarea', 'Pozdrav iz brskalnika')
await A.keyboard.press('Enter')
await B.waitForFunction(() => document.querySelector('.chat-msgs')?.textContent.includes('Pozdrav iz brskalnika'), { timeout: 4000 })
ok(true, 'Borut je prejel sporočilo v živo (SSE)')
const chip = await B.$eval('.chat-msgs .chat-machine', (e) => e.textContent)
ok(chip === 'Okuma Genos', 'oznaka stroja prikazana: ' + chip)
// Borut: kljukica
await B.click('.chat-msg [data-done]')
await A.waitForFunction(() => document.querySelector('.chat-msg.is-done'), { timeout: 4000 })
ok(true, 'kljukica se prenese k Ani')
// Borut: fokus + osnutek ohranjen ob render()
await B.click('.chat textarea'); await B.type('.chat textarea', 'osnutek')
await B.evaluate(() => { location.hash = '#/klepet/plani?x'; })
await B.evaluate(() => { location.hash = '#/klepet/plani' })
await sleep(300)
const st = await B.evaluate(() => ({ f: document.activeElement?.tagName, v: document.querySelector('.chat textarea').value }))
ok(st.f === 'TEXTAREA' && st.v === 'osnutek', 'fokus in osnutek ohranjena po render(): ' + JSON.stringify(st))
// neprebrano v Nujno: Ana pošlje v nujno, Borut je v Plani
await A.click('[data-ch="nujno"]'); await A.type('.chat textarea', 'NUJNO test'); await A.keyboard.press('Enter')
await B.waitForFunction(() => document.querySelector('[data-ch="nujno"] .chat-unread')?.textContent === '1', { timeout: 4000 })
ok(true, 'števec neprebranega pri Nujno = 1')
const tabBadge = await B.$eval('[data-chat-badge]', (e) => e.textContent + (e.hidden ? ' hidden' : ''))
ok(tabBadge === '1', 'značka na zavihku: ' + tabBadge)
await B.click('[data-ch="nujno"]')
await B.waitForFunction(() => !document.querySelector('[data-ch="nujno"] .chat-unread'), { timeout: 4000 })
ok(true, 'neprebrano izgine ob odprtju kanala')
// iskanje
await B.click('.chat-head button'); await B.type('.chat-search input', 'brskalnika')
await B.waitForSelector('.chat-hit', { timeout: 4000 })
await B.click('.chat-hit')
await B.waitForFunction(() => document.querySelector('.chat-title').textContent.includes('Plani'), { timeout: 4000 })
ok(true, 'iskanje + skok na sporočilo')
// obstoječe zavihke
await B.click('[data-tab="nabava"]'); await sleep(200)
ok(!!(await B.$('main .card, main form, main section')), 'zavihek Nabava še dela')
await B.click('[data-tab="klepet"]'); await sleep(200)
ok(!!(await B.$('.chat textarea')), 'nazaj v Klepet')

// ---- Kaj se mudi (tabla)
const yday = await B.evaluate(() => { const d = new Date(); d.setDate(d.getDate() - 1); const p = (n) => String(n).padStart(2, '0'); return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}` })
await B.click('[data-tab="mudi"]'); await B.waitForSelector('.mudi-form')
await B.type('.mudi-form [name="wo"]', '24-0815'); await B.type('.mudi-form [name="customer"]', 'Gorenje'); await B.type('.mudi-form [name="text"]', 'Prevrtaj luknje')
await B.$eval('.mudi-form [name="date"]', (el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })) }, yday)
await B.click('.mudi-machine-btn'); await B.click('.mudi-tag [data-machine="MB-46VAE"]')
await B.click('.mudi-add')
await B.waitForSelector('.mudi-item.d-overdue', { timeout: 4000 })
const lbl = await B.$eval('.mudi-item .mudi-date', (e) => e.textContent)
ok(/^ZAPADLO/.test(lbl), 'dodano; zapadla postavka poudarjena: ' + lbl)
await A.waitForFunction(() => { const s = document.querySelector('[data-mudi-strip]'); return s && !s.hidden && /Kaj se mudi: 1/.test(s.textContent) }, { timeout: 5000 })
ok(true, 'pas "Kaj se mudi: 1" se pri Ani pokaže v živo')
const stripTxt = await A.$eval('[data-mudi-strip]', (e) => e.textContent)
ok(/24-0815/.test(stripTxt) && /zapadlo 1/.test(stripTxt), 'pas: ' + stripTxt)
await A.waitForFunction(() => document.querySelector('.toast')?.textContent.includes('Kaj se mudi'), { timeout: 3000 })
ok(true, 'toast v aplikaciji za novo postavko')
// fokus ohranjen
await B.click('.mudi-form [name="wo"]'); await B.type('.mudi-form [name="wo"]', 'abc')
await B.evaluate(() => { location.hash = '#/mudi'; window.dispatchEvent(new HashChangeEvent('hashchange')) })
await sleep(300)
const bf = await B.evaluate(() => ({ n: document.activeElement?.name, v: document.querySelector('.mudi-form [name="wo"]').value }))
ok(bf.n === 'wo' && bf.v === 'abc', 'fokus in vnos ohranjena po render(): ' + JSON.stringify(bf))
// Ana: Narejeno
await A.click('[data-tab="mudi"]'); await A.waitForSelector('.mudi-item [data-done]')
await A.click('.mudi-item [data-done]')
await B.waitForFunction(() => document.querySelector('.mudi-empty'), { timeout: 4000 })
ok(true, 'kljukica Narejeno: pri Borutu izgine (Vse mirno)')
await A.click('[data-tab="nabava"]'); await sleep(200)
const hid = await A.$eval('[data-mudi-strip]', (e) => e.hidden)
ok(hid, 'pas skrit, ko ni odprtih')
await browser.close()
console.log(fails ? `FAILED ${fails}` : 'ALL OK'); process.exit(fails ? 1 : 0)
